"""goida6

Revision ID: 10c20bf295d7
Revises: 6c08e7091c4c
Create Date: 2025-04-26 16:59:30.024623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10c20bf295d7'
down_revision: Union[str, None] = '6c08e7091c4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_groups_date'), 'user_groups', ['date'], unique=False)
    op.create_index(op.f('ix_user_groups_id'), 'user_groups', ['id'], unique=False)
    op.create_table('user_courses_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.SmallInteger(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_courses_groups_course_id'), 'user_courses_groups', ['course_id'], unique=False)
    op.create_index(op.f('ix_user_courses_groups_group_id'), 'user_courses_groups', ['group_id'], unique=False)
    op.create_index(op.f('ix_user_courses_groups_id'), 'user_courses_groups', ['id'], unique=False)
    op.create_table('user_clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('initials', sa.String(), nullable=True),
    sa.Column('inn', sa.String(), nullable=True),
    sa.Column('org', sa.String(), nullable=True),
    sa.Column('safety', sa.Integer(), nullable=True),
    sa.Column('reg_num', sa.Integer(), nullable=True),
    sa.Column('course_group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_group_id'], ['courses_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_clients_course_group_id'), 'user_clients', ['course_group_id'], unique=False)
    op.create_index(op.f('ix_user_clients_id'), 'user_clients', ['id'], unique=False)
    op.create_index(op.f('ix_user_clients_initials'), 'user_clients', ['initials'], unique=False)
    op.create_index(op.f('ix_user_clients_inn'), 'user_clients', ['inn'], unique=False)
    op.create_index(op.f('ix_user_clients_org'), 'user_clients', ['org'], unique=False)
    op.create_index(op.f('ix_user_clients_reg_num'), 'user_clients', ['reg_num'], unique=False)
    op.create_index(op.f('ix_user_clients_safety'), 'user_clients', ['safety'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_clients_safety'), table_name='user_clients')
    op.drop_index(op.f('ix_user_clients_reg_num'), table_name='user_clients')
    op.drop_index(op.f('ix_user_clients_org'), table_name='user_clients')
    op.drop_index(op.f('ix_user_clients_inn'), table_name='user_clients')
    op.drop_index(op.f('ix_user_clients_initials'), table_name='user_clients')
    op.drop_index(op.f('ix_user_clients_id'), table_name='user_clients')
    op.drop_index(op.f('ix_user_clients_course_group_id'), table_name='user_clients')
    op.drop_table('user_clients')
    op.drop_index(op.f('ix_user_courses_groups_id'), table_name='user_courses_groups')
    op.drop_index(op.f('ix_user_courses_groups_group_id'), table_name='user_courses_groups')
    op.drop_index(op.f('ix_user_courses_groups_course_id'), table_name='user_courses_groups')
    op.drop_table('user_courses_groups')
    op.drop_index(op.f('ix_user_groups_id'), table_name='user_groups')
    op.drop_index(op.f('ix_user_groups_date'), table_name='user_groups')
    op.drop_table('user_groups')
    # ### end Alembic commands ###
