"""zv13

Revision ID: 15e42d97c0f5
Revises: eae8f6994036
Create Date: 2025-06-30 03:36:20.634608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15e42d97c0f5'
down_revision: Union[str, None] = 'eae8f6994036'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('org_inn', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('snils', sa.String(), nullable=True))
    op.create_index(op.f('ix_clients_org_inn'), 'clients', ['org_inn'], unique=False)
    op.create_index(op.f('ix_clients_snils'), 'clients', ['snils'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clients_snils'), table_name='clients')
    op.drop_index(op.f('ix_clients_org_inn'), table_name='clients')
    op.drop_column('clients', 'snils')
    op.drop_column('clients', 'org_inn')
    # ### end Alembic commands ###
