"""goida2

Revision ID: 1662e0c2e522
Revises: 956a18c3795d
Create Date: 2025-04-20 16:19:56.037021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1662e0c2e522'
down_revision: Union[str, None] = '956a18c3795d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_courses_groups_date', table_name='courses_groups')
    op.drop_column('courses_groups', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses_groups', sa.Column('date', sa.DATE(), autoincrement=False, nullable=True))
    op.create_index('ix_courses_groups_date', 'courses_groups', ['date'], unique=False)
    # ### end Alembic commands ###
