"""zv5

Revision ID: 1665103af7a6
Revises: bdb7f82b9a84
Create Date: 2025-05-10 16:44:15.812352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1665103af7a6'
down_revision: Union[str, None] = 'bdb7f82b9a84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('metodists', 'lvl')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metodists', sa.Column('lvl', sa.SMALLINT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
