"""goida8

Revision ID: 18cd1e4b32f9
Revises: 33a53f8bc34b
Create Date: 2025-04-26 17:17:51.184778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18cd1e4b32f9'
down_revision: Union[str, None] = '33a53f8bc34b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_clients_course_group_id_fkey', 'user_clients', type_='foreignkey')
    op.create_foreign_key(None, 'user_clients', 'user_courses_groups', ['course_group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_clients', type_='foreignkey')
    op.create_foreign_key('user_clients_course_group_id_fkey', 'user_clients', 'courses_groups', ['course_group_id'], ['id'])
    # ### end Alembic commands ###
