"""goida14

Revision ID: 1fb150f3e8b3
Revises: b2a359636a15
Create Date: 2025-04-28 03:10:39.740957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fb150f3e8b3'
down_revision: Union[str, None] = 'b2a359636a15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('teachers_group_teacher_id_fkey', 'teachers_group', type_='foreignkey')
    op.create_foreign_key(None, 'teachers_group', 'teachers', ['teacher_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teachers_group', type_='foreignkey')
    op.create_foreign_key('teachers_group_teacher_id_fkey', 'teachers_group', 'teachers', ['teacher_id'], ['id'])
    # ### end Alembic commands ###
