"""goida12

Revision ID: 58f0ee277002
Revises: 9ee15c8294ba
Create Date: 2025-04-27 04:18:50.104550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58f0ee277002'
down_revision: Union[str, None] = '9ee15c8294ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teachers_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teachers_group_group_id'), 'teachers_group', ['group_id'], unique=False)
    op.create_index(op.f('ix_teachers_group_id'), 'teachers_group', ['id'], unique=False)
    op.create_index(op.f('ix_teachers_group_teacher_id'), 'teachers_group', ['teacher_id'], unique=False)
    op.drop_index('ix_staff_group_group_id', table_name='staff_group')
    op.drop_index('ix_staff_group_id', table_name='staff_group')
    op.drop_index('ix_staff_group_teacher_id', table_name='staff_group')
    op.drop_table('staff_group')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff_group',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name='staff_group_group_id_fkey'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], name='staff_group_teacher_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='staff_group_pkey')
    )
    op.create_index('ix_staff_group_teacher_id', 'staff_group', ['teacher_id'], unique=False)
    op.create_index('ix_staff_group_id', 'staff_group', ['id'], unique=False)
    op.create_index('ix_staff_group_group_id', 'staff_group', ['group_id'], unique=False)
    op.drop_index(op.f('ix_teachers_group_teacher_id'), table_name='teachers_group')
    op.drop_index(op.f('ix_teachers_group_id'), table_name='teachers_group')
    op.drop_index(op.f('ix_teachers_group_group_id'), table_name='teachers_group')
    op.drop_table('teachers_group')
    # ### end Alembic commands ###
