"""zv10

Revision ID: 68defdbf844b
Revises: 795a2a38654a
Create Date: 2025-05-13 15:29:54.887994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '68defdbf844b'
down_revision: Union[str, None] = '795a2a38654a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.String(), nullable=True),
    sa.Column('key', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_fields_course_id'), 'course_fields', ['course_id'], unique=False)
    op.create_index(op.f('ix_course_fields_id'), 'course_fields', ['id'], unique=False)
    op.create_index(op.f('ix_course_fields_key'), 'course_fields', ['key'], unique=False)
    op.drop_column('courses', 'fields')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('fields', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_course_fields_key'), table_name='course_fields')
    op.drop_index(op.f('ix_course_fields_id'), table_name='course_fields')
    op.drop_index(op.f('ix_course_fields_course_id'), table_name='course_fields')
    op.drop_table('course_fields')
    # ### end Alembic commands ###
