"""initial

Revision ID: 71c58224d385
Revises: 
Create Date: 2025-04-13 23:22:22.553717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71c58224d385'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.SmallInteger(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_groups_course_id'), 'groups', ['course_id'], unique=False)
    op.create_index(op.f('ix_groups_date'), 'groups', ['date'], unique=False)
    op.create_index(op.f('ix_groups_id'), 'groups', ['id'], unique=False)
    op.create_table('metodists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(), nullable=True),
    sa.Column('lvl', sa.SmallInteger(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metodists_id'), 'metodists', ['id'], unique=False)
    op.create_index(op.f('ix_metodists_login'), 'metodists', ['login'], unique=False)
    op.create_table('teachers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('initials', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teachers_id'), 'teachers', ['id'], unique=False)
    op.create_index(op.f('ix_teachers_initials'), 'teachers', ['initials'], unique=False)
    op.create_index(op.f('ix_teachers_status'), 'teachers', ['status'], unique=False)
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('initials', sa.String(), nullable=True),
    sa.Column('inn', sa.String(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('org', sa.String(), nullable=True),
    sa.Column('reason_check', sa.Integer(), nullable=True),
    sa.Column('safety', sa.Integer(), nullable=True),
    sa.Column('result_check', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_group_id'), 'clients', ['group_id'], unique=False)
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
    op.create_index(op.f('ix_clients_initials'), 'clients', ['initials'], unique=False)
    op.create_index(op.f('ix_clients_inn'), 'clients', ['inn'], unique=False)
    op.create_index(op.f('ix_clients_org'), 'clients', ['org'], unique=False)
    op.create_index(op.f('ix_clients_reason_check'), 'clients', ['reason_check'], unique=False)
    op.create_index(op.f('ix_clients_result_check'), 'clients', ['result_check'], unique=False)
    op.create_index(op.f('ix_clients_safety'), 'clients', ['safety'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clients_safety'), table_name='clients')
    op.drop_index(op.f('ix_clients_result_check'), table_name='clients')
    op.drop_index(op.f('ix_clients_reason_check'), table_name='clients')
    op.drop_index(op.f('ix_clients_org'), table_name='clients')
    op.drop_index(op.f('ix_clients_inn'), table_name='clients')
    op.drop_index(op.f('ix_clients_initials'), table_name='clients')
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_group_id'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_teachers_status'), table_name='teachers')
    op.drop_index(op.f('ix_teachers_initials'), table_name='teachers')
    op.drop_index(op.f('ix_teachers_id'), table_name='teachers')
    op.drop_table('teachers')
    op.drop_index(op.f('ix_metodists_login'), table_name='metodists')
    op.drop_index(op.f('ix_metodists_id'), table_name='metodists')
    op.drop_table('metodists')
    op.drop_index(op.f('ix_groups_id'), table_name='groups')
    op.drop_index(op.f('ix_groups_date'), table_name='groups')
    op.drop_index(op.f('ix_groups_course_id'), table_name='groups')
    op.drop_table('groups')
    # ### end Alembic commands ###
