"""zv9

Revision ID: 795a2a38654a
Revises: c2902394ebd9
Create Date: 2025-05-13 15:28:57.945342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '795a2a38654a'
down_revision: Union[str, None] = 'c2902394ebd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_teachers_id', table_name='teachers')
    op.drop_index('ix_teachers_initials', table_name='teachers')
    op.drop_index('ix_teachers_status', table_name='teachers')
    op.drop_table('teachers')
    op.drop_index('ix_clients_course_group_id', table_name='clients')
    op.drop_index('ix_clients_id', table_name='clients')
    op.drop_index('ix_clients_initials', table_name='clients')
    op.drop_index('ix_clients_inn', table_name='clients')
    op.drop_index('ix_clients_org', table_name='clients')
    op.drop_index('ix_clients_reg_num', table_name='clients')
    op.drop_index('ix_clients_safety', table_name='clients')
    op.drop_table('clients')
    op.drop_index('ix_courses_id', table_name='courses')
    op.drop_index('ix_courses_name', table_name='courses')
    op.drop_table('courses')
    op.drop_index('ix_metodists_id', table_name='metodists')
    op.drop_index('ix_metodists_login', table_name='metodists')
    op.drop_table('metodists')
    op.drop_index('ix_groups_date', table_name='groups')
    op.drop_index('ix_groups_id', table_name='groups')
    op.drop_index('ix_groups_isOrder', table_name='groups')
    op.drop_table('groups')
    op.drop_index('ix_teachers_group_group_id', table_name='teachers_group')
    op.drop_index('ix_teachers_group_id', table_name='teachers_group')
    op.drop_index('ix_teachers_group_teacher_id', table_name='teachers_group')
    op.drop_table('teachers_group')
    op.drop_index('ix_courses_groups_course_id', table_name='courses_groups')
    op.drop_index('ix_courses_groups_group_id', table_name='courses_groups')
    op.drop_index('ix_courses_groups_id', table_name='courses_groups')
    op.drop_table('courses_groups')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses_groups',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('courses_groups_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name='courses_groups_course_id_fkey'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name='courses_groups_group_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='courses_groups_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_courses_groups_id', 'courses_groups', ['id'], unique=False)
    op.create_index('ix_courses_groups_group_id', 'courses_groups', ['group_id'], unique=False)
    op.create_index('ix_courses_groups_course_id', 'courses_groups', ['course_id'], unique=False)
    op.create_table('teachers_group',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name='teachers_group_group_id_fkey'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], name='teachers_group_teacher_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='teachers_group_pkey')
    )
    op.create_index('ix_teachers_group_teacher_id', 'teachers_group', ['teacher_id'], unique=False)
    op.create_index('ix_teachers_group_id', 'teachers_group', ['id'], unique=False)
    op.create_index('ix_teachers_group_group_id', 'teachers_group', ['group_id'], unique=False)
    op.create_table('groups',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('groups_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('isOrder', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='groups_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_groups_isOrder', 'groups', ['isOrder'], unique=False)
    op.create_index('ix_groups_id', 'groups', ['id'], unique=False)
    op.create_index('ix_groups_date', 'groups', ['date'], unique=False)
    op.create_table('metodists',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('login', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='metodists_pkey')
    )
    op.create_index('ix_metodists_login', 'metodists', ['login'], unique=False)
    op.create_index('ix_metodists_id', 'metodists', ['id'], unique=False)
    op.create_table('courses',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('courses_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('hours', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fields', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='courses_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_courses_name', 'courses', ['name'], unique=False)
    op.create_index('ix_courses_id', 'courses', ['id'], unique=False)
    op.create_table('clients',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('initials', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('inn', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('org', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('safety', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reg_num', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('course_group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['course_group_id'], ['courses_groups.id'], name='clients_course_group_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='clients_pkey')
    )
    op.create_index('ix_clients_safety', 'clients', ['safety'], unique=False)
    op.create_index('ix_clients_reg_num', 'clients', ['reg_num'], unique=False)
    op.create_index('ix_clients_org', 'clients', ['org'], unique=False)
    op.create_index('ix_clients_inn', 'clients', ['inn'], unique=False)
    op.create_index('ix_clients_initials', 'clients', ['initials'], unique=False)
    op.create_index('ix_clients_id', 'clients', ['id'], unique=False)
    op.create_index('ix_clients_course_group_id', 'clients', ['course_group_id'], unique=False)
    op.create_table('teachers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('initials', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='teachers_pkey')
    )
    op.create_index('ix_teachers_status', 'teachers', ['status'], unique=False)
    op.create_index('ix_teachers_initials', 'teachers', ['initials'], unique=False)
    op.create_index('ix_teachers_id', 'teachers', ['id'], unique=False)
    # ### end Alembic commands ###
