"""goida3

Revision ID: 7f242a85ba9f
Revises: 1662e0c2e522
Create Date: 2025-04-20 16:52:17.680204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f242a85ba9f'
down_revision: Union[str, None] = '1662e0c2e522'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_clients_reason_check', table_name='clients')
    op.drop_index('ix_clients_result_check', table_name='clients')
    op.drop_column('clients', 'reason_check')
    op.drop_column('clients', 'result_check')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('result_check', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('clients', sa.Column('reason_check', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_index('ix_clients_result_check', 'clients', ['result_check'], unique=False)
    op.create_index('ix_clients_reason_check', 'clients', ['reason_check'], unique=False)
    # ### end Alembic commands ###
