"""goida11

Revision ID: 9ee15c8294ba
Revises: b2099a549389
Create Date: 2025-04-27 04:01:23.004344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ee15c8294ba'
down_revision: Union[str, None] = 'b2099a549389'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_group_group_id'), 'staff_group', ['group_id'], unique=False)
    op.create_index(op.f('ix_staff_group_id'), 'staff_group', ['id'], unique=False)
    op.create_index(op.f('ix_staff_group_teacher_id'), 'staff_group', ['teacher_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_staff_group_teacher_id'), table_name='staff_group')
    op.drop_index(op.f('ix_staff_group_id'), table_name='staff_group')
    op.drop_index(op.f('ix_staff_group_group_id'), table_name='staff_group')
    op.drop_table('staff_group')
    # ### end Alembic commands ###
