"""zv3

Revision ID: ad42f2602c04
Revises: 0bb52fb6e2c7
Create Date: 2025-05-10 16:10:57.875733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad42f2602c04'
down_revision: Union[str, None] = '0bb52fb6e2c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('metodists', 'lvl')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metodists', sa.Column('lvl', sa.SMALLINT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
