"""goida10

Revision ID: b2099a549389
Revises: 56707bd7435e
Create Date: 2025-04-26 17:29:32.474784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2099a549389'
down_revision: Union[str, None] = '56707bd7435e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_courses_groups_group_id_fkey', 'user_courses_groups', type_='foreignkey')
    op.create_foreign_key(None, 'user_courses_groups', 'user_groups', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_courses_groups', type_='foreignkey')
    op.create_foreign_key('user_courses_groups_group_id_fkey', 'user_courses_groups', 'groups', ['group_id'], ['id'])
    # ### end Alembic commands ###
