"""goida

Revision ID: e351af77c55b
Revises: 71c58224d385
Create Date: 2025-04-19 12:39:26.770022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e351af77c55b'
down_revision: Union[str, None] = '71c58224d385'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.SmallInteger(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courses_groups_course_id'), 'courses_groups', ['course_id'], unique=False)
    op.create_index(op.f('ix_courses_groups_date'), 'courses_groups', ['date'], unique=False)
    op.create_index(op.f('ix_courses_groups_group_id'), 'courses_groups', ['group_id'], unique=False)
    op.create_index(op.f('ix_courses_groups_id'), 'courses_groups', ['id'], unique=False)
    op.add_column('clients', sa.Column('course_group_id', sa.Integer(), nullable=True))
    op.drop_index('ix_clients_group_id', table_name='clients')
    op.create_index(op.f('ix_clients_course_group_id'), 'clients', ['course_group_id'], unique=False)
    op.drop_constraint('clients_group_id_fkey', 'clients', type_='foreignkey')
    op.create_foreign_key(None, 'clients', 'courses_groups', ['course_group_id'], ['id'])
    op.drop_column('clients', 'group_id')
    op.drop_index('ix_groups_course_id', table_name='groups')
    op.drop_column('groups', 'course_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('course_id', sa.SMALLINT(), autoincrement=False, nullable=True))
    op.create_index('ix_groups_course_id', 'groups', ['course_id'], unique=False)
    op.add_column('clients', sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.create_foreign_key('clients_group_id_fkey', 'clients', 'groups', ['group_id'], ['id'])
    op.drop_index(op.f('ix_clients_course_group_id'), table_name='clients')
    op.create_index('ix_clients_group_id', 'clients', ['group_id'], unique=False)
    op.drop_column('clients', 'course_group_id')
    op.drop_index(op.f('ix_courses_groups_id'), table_name='courses_groups')
    op.drop_index(op.f('ix_courses_groups_group_id'), table_name='courses_groups')
    op.drop_index(op.f('ix_courses_groups_date'), table_name='courses_groups')
    op.drop_index(op.f('ix_courses_groups_course_id'), table_name='courses_groups')
    op.drop_table('courses_groups')
    # ### end Alembic commands ###
