"""goida4

Revision ID: ea5a46a2f6f2
Revises: 7f242a85ba9f
Create Date: 2025-04-23 12:27:12.888748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea5a46a2f6f2'
down_revision: Union[str, None] = '7f242a85ba9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('reg_num', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_clients_reg_num'), 'clients', ['reg_num'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clients_reg_num'), table_name='clients')
    op.drop_column('clients', 'reg_num')
    # ### end Alembic commands ###
