"""zv12

Revision ID: eae8f6994036
Revises: 6091dd8267b9
Create Date: 2025-06-23 02:51:15.185903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eae8f6994036'
down_revision: Union[str, None] = '6091dd8267b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('position', sa.String(), nullable=True))
    op.create_index(op.f('ix_clients_position'), 'clients', ['position'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clients_position'), table_name='clients')
    op.drop_column('clients', 'position')
    # ### end Alembic commands ###
